# Numpy 

## Numpy arrays

In [13]:
import numpy as np

In [3]:
a = np.array([1,2,3])

In [5]:
a[0], a[1], a[2]

(1, 2, 3)

In [7]:
a[0:-1]

array([1, 2])

In [8]:
a[[0,2]]

array([1, 3])

## Array Types

In [9]:
a.dtype

dtype('int32')

In [10]:
np.array([1, 2, 3], dtype=np.float)

array([1., 2., 3.])

In [11]:
np.array(['a', 'b', 'c']).dtype

dtype('<U1')

In [15]:
np.array([{'a': 1}, 'b']).dtype

dtype('O')

## Dimensions and shapes

In [16]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [17]:
A.shape

(2, 3)

In [18]:
A.ndim

2

In [19]:
A.size

6

In [20]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

C:\Users\Zoey\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  import sys


In [21]:
B.dtype

dtype('O')

In [22]:
B.shape

(2,)

In [23]:
B.size

2

In [24]:
type(B[0])

list

## Indexing and Slicing of Matrices

In [25]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9] 
])

In [26]:
A[1]

array([4, 5, 6])

In [27]:
A[0][1]

2

In [28]:
A[1, 0]

4

In [30]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [32]:
A[2] = 99

In [33]:
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [99, 99, 99]])

## statistics

In [35]:
a = np.array([1, 2, 3, 4])

In [36]:
a.sum()

10

In [37]:
a.mean()

2.5

In [38]:
a.std()

1.118033988749895

In [39]:
a.var()

1.25

In [40]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [41]:
A.sum()

45

In [42]:
A.sum(axis=0)

array([12, 15, 18])

In [43]:
A.mean(axis=1)

array([2., 5., 8.])

And [many more](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html#array-methods)

## Broadcasting and Vectorized operations

In [48]:
np.arange(4)

array([0, 1, 2, 3])

In [46]:
a = np.arange(4)

In [47]:
a + 10

array([10, 11, 12, 13])

## Boolean arrays

In [49]:
a = np.arange(4)

In [50]:
a[[True, False, False, True]]

array([0, 3])

In [51]:
a >= 2

array([False, False,  True,  True])

In [52]:
a[a >= 2]

array([2, 3])

## Linear Algebra

In [53]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [54]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [55]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [56]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [57]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

## random

In [58]:
np.random.random(size=2)

array([0.1095247 , 0.20183054])

In [59]:
np.random.normal(size=2)

array([ 0.09609213, -0.38523674])

In [60]:
np.random.rand(2, 4)

array([[0.40106817, 0.80502126, 0.81027943, 0.03343326],
       [0.73806669, 0.3298318 , 0.09700509, 0.13122684]])

##  arange

In [61]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [63]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

## reshape

In [64]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## linspace

In [65]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [67]:
np.linspace(0, 1, 5, False)

array([0. , 0.2, 0.4, 0.6, 0.8])

## zeros, ones, empty

In [68]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [69]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [70]:
np.empty((2, 2))

array([[0.2, 0.4],
       [0.6, 0.8]])

## identity and eye

In [71]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [72]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [73]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])